# Starship configuration

container.disabled = true
git_branch.disabled = true
git_commit.disabled = true
git_state.disabled = true
git_status.disabled = true
package.disabled = true

[directory]
truncation_length = 7
truncation_symbol = '…/'

[hostname]
ssh_only = false

[username]
show_always = true
